// Code generated by Kitex v0.5.0. DO NOT EDIT.
package echoservice

import (
	server "github.com/cloudwego/kitex/server"
	echo "github.com/felix021/kitex-test/kitex_gen/echo"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler echo.EchoService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
