// Code generated by Kitex v0.4.4. DO NOT EDIT.
package echo

import (
	server "github.com/cloudwego/kitex/server"
	pbapi "github.com/felix021/kitex-test/kitex_gen/pbapi"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler pbapi.Echo, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
