# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x05pbapi\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t21\n\x04\x45\x63ho\x12)\n\x04\x45\x63ho\x12\x0e.pbapi.Request\x1a\x0f.pbapi.Response\"\x00\x42\x07Z\x05pbapib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\005pbapi'
  _REQUEST._serialized_start=20
  _REQUEST._serialized_end=46
  _RESPONSE._serialized_start=48
  _RESPONSE._serialized_end=75
  _ECHO._serialized_start=77
  _ECHO._serialized_end=126
# @@protoc_insertion_point(module_scope)
